# Generated by Django 3.0.3 on 2020-03-09 16:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('agreement_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(default=None, max_length=50)),
                ('assigned_hours', models.FloatField()),
                ('fly_hours', models.FloatField()),
                ('total_hours', models.FloatField()),
                ('next_inspection', models.FloatField()),
                ('next_inspection_hours', models.FloatField()),
                ('aircraft_status', models.CharField(choices=[('ACL', 'Aeronave Completamente lista'), ('LRM', 'Aeronave Lista con Restricciones por Mantenimiento'), ('LRA', 'Aeronave Lista con Restricciones por Abastecimiento'), ('AMI', 'Aeronave en Mantenimiento Imprevisto'), ('AMP', 'Aeronave en mantenimiento Programado'), ('NLA', 'Aeronave No Lista por Abastecimientos'), ('AVP', 'Aeronave en Vuelo de Prueba'), ('MMP', 'Aeronave en Mantenimiento Mayor Programado'), ('AMO', 'Aeronave en Mantenimiento Modificativo'), ('AMR', 'Aeronave en Mantenimiento Recuperativo'), ('ACC', 'Aeronave Accidentada'), ('EVA', 'Aeronave en Evaluacion'), ('PAR', 'Aeronave Pendiente Asignacion de Recursos'), ('ABP', 'Aeronave en Proeso de Baja'), ('APA', 'Aeronave en proceso de Alta')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AirCraftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AirCraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AviationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='AviationMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='index.AviationMission')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('flight_charge', models.CharField(choices=[('PAM', 'Piloto al Mando'), ('P', 'Piloto'), ('IV', 'Ingeniero de vuelo'), ('JT', 'Jefe de Tripulacion'), ('TV', 'Tecnico de vuelo'), ('ART', 'Artillero'), ('CMA', 'Comandante de misión aérea'), ('OMI', 'Operador de Mision'), ('OVE', 'Operador de vehiculo')], max_length=3)),
                ('air_craft_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts_model_crew', to='index.AirCraftModel')),
                ('air_craft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts_type_crew', to='index.AirCraftType')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('initials', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MajorOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MajorOperativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_ejc', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinorOperativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_ejc', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('major_operative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_operative_units', to='index.MajorOperativeUnit')),
            ],
        ),
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TacticUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_aviation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('minor_operative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_units', to='index.MinorOperativeUnit')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_users', to='index.Rank')),
                ('tactic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_unit_users', to='index.TacticUnit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type_users', to='index.UserType')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('major_operations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_operations', to='index.MajorOperation')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='index.Department')),
            ],
        ),
        migrations.CreateModel(
            name='FlightReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.CharField(max_length=50)),
                ('fuel', models.FloatField()),
                ('kilos', models.FloatField()),
                ('sick_pt', models.IntegerField()),
                ('wounded_pt', models.IntegerField()),
                ('dead_pt', models.IntegerField()),
                ('sick_en', models.IntegerField()),
                ('wounded_en', models.IntegerField()),
                ('dead_en', models.IntegerField()),
                ('civil_evacuations', models.IntegerField()),
                ('pax', models.IntegerField()),
                ('crew_hours', models.FloatField()),
                ('machine_hours', models.FloatField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_aircraft', to='index.AirCraft')),
                ('aviation_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_events', to='index.AviationEvent')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_configurations', to='index.Configuration')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_crew', to='index.Crew')),
                ('flight_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_conditions', to='index.FlightCondition')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_mission', to='index.AviationMission')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_municipalities', to='index.Municipality')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_operations', to='index.Operation')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_crew', to='index.Rank'),
        ),
        migrations.AddField(
            model_name='aviationmission',
            name='mission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviation_mission_type', to='index.MissionType'),
        ),
        migrations.AddField(
            model_name='aviationevent',
            name='minicipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviation_events_municipalities', to='index.Municipality'),
        ),
        migrations.CreateModel(
            name='AirCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_crews', to='index.Crew')),
                ('flight_reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='index.FlightReport')),
            ],
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='air_craft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraftmodels', to='index.AirCraftType'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='air_craft_models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_models', to='index.AirCraftModel'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='air_craft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_types', to='index.AirCraftType'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_municipalities', to='index.Municipality'),
        ),
    ]
