# Generated by Django 3.0.3 on 2020-05-08 22:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('agreement_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(default=None, max_length=50)),
                ('assigned_hours', models.FloatField()),
                ('re_asign', models.FloatField(default=0)),
                ('merger_hours', models.FloatField(default=0)),
                ('hours_available', models.FloatField(default=0)),
                ('fly_hours', models.FloatField()),
                ('total_hours', models.FloatField()),
                ('next_inspection', models.FloatField()),
                ('next_inspection_hours', models.FloatField(blank=True, default=0)),
                ('type_inspection', models.CharField(max_length=50, null=True)),
                ('aircraft_status', models.CharField(choices=[('ACL', 'Aeronave Completamente lista'), ('LRM', 'Aeronave Lista con Restricciones por Mantenimiento'), ('LRA', 'Aeronave Lista con Restricciones por Abastecimiento'), ('AMI', 'Aeronave en Mantenimiento Imprevisto'), ('AMP', 'Aeronave en mantenimiento Programado'), ('NLA', 'Aeronave No Lista por Abastecimientos'), ('AVP', 'Aeronave en Vuelo de Prueba'), ('MMP', 'Aeronave en Mantenimiento Mayor Programado'), ('AMO', 'Aeronave en Mantenimiento Modificativo'), ('AMR', 'Aeronave en Mantenimiento Recuperativo'), ('ACC', 'Aeronave Accidentada'), ('EVA', 'Aeronave en Evaluacion'), ('PAR', 'Aeronave Pendiente Asignacion de Recursos'), ('ABP', 'Aeronave en Proeso de Baja'), ('APA', 'Aeronave en proceso de Alta')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AirCraftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('has_pam', models.BooleanField(default=False)),
                ('has_pilot', models.BooleanField(default=False)),
                ('has_flight_engineer', models.BooleanField(default=False)),
                ('has_crew_chief', models.BooleanField(default=False)),
                ('has_flight_technician', models.BooleanField(default=False)),
                ('has_gunner', models.BooleanField(default=False)),
                ('has_commander', models.BooleanField(default=False)),
                ('has_mission_operator', models.BooleanField(default=False)),
                ('has_vehicle_operator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AirCraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AviationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DB', 'Daño de batalla'), ('BASH', 'BASH - Bird/wildlife aircraft strike hazzard'), ('FOD', 'FOD - Foreign object damage'), ('CFIT', 'CFIT - Controlled Flight InTo Terrain'), ('CO', 'Colision'), ('IP', 'Incursión de pista')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='AviationMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='index.AviationMission')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('initials', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MajorOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MajorOperativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_ejc', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinorOperativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_ejc', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('major_operative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_operative_units', to='index.MajorOperativeUnit')),
            ],
        ),
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TacticUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_aviation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('minor_operative_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_units', to='index.MinorOperativeUnit')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
                ('code', models.IntegerField(default=1, error_messages={'unique': 'Ya existe este usuario.'}, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_users', to='index.Rank')),
                ('tactic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_unit_users', to='index.TacticUnit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type_users', to='index.UserType')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('major_operations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_operations', to='index.MajorOperation')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='index.Department')),
            ],
        ),
        migrations.CreateModel(
            name='FlightReport',
            fields=[
                ('flight_order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('risk_classification', models.CharField(blank=True, choices=[('HIGH', 'RIESGO ALTO'), ('MED', 'RIESGO MEDIO'), ('LOW', 'RIESGO BAJO')], max_length=4, null=True)),
                ('route', models.CharField(max_length=1000)),
                ('observations', models.CharField(blank=True, max_length=1000, null=True)),
                ('fuel', models.FloatField(blank=True, null=True)),
                ('kilos', models.FloatField(blank=True, null=True)),
                ('sick_pt', models.IntegerField(blank=True, null=True)),
                ('wounded_pt', models.IntegerField(blank=True, null=True)),
                ('dead_pt', models.IntegerField(blank=True, null=True)),
                ('sick_en', models.IntegerField(blank=True, null=True)),
                ('wounded_en', models.IntegerField(blank=True, null=True)),
                ('dead_en', models.IntegerField(blank=True, null=True)),
                ('civil_evacuations', models.IntegerField(blank=True, null=True)),
                ('pax', models.IntegerField(blank=True, null=True)),
                ('crew_hours', models.FloatField(blank=True, null=True)),
                ('machine_hours', models.FloatField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_agreements', to='index.Agreement')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_aircrafts', to='index.AirCraft')),
                ('aviation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_events', to='index.AviationEvent')),
                ('aviation_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_aviation_missions', to='index.AviationMission')),
                ('aviation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_aviation_units', to='index.TacticUnit')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_configurations', to='index.Configuration')),
                ('flight_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_conditions', to='index.FlightCondition')),
                ('major_operative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_major_operative_units', to='index.MajorOperativeUnit')),
                ('minor_operative_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_minor_operative_units', to='index.MinorOperativeUnit')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_municipalities', to='index.Municipality')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_operations', to='index.Operation')),
                ('tactic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_tactic_units', to='index.TacticUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('flight_charge', models.CharField(choices=[('PAM', 'Piloto al Mando'), ('P', 'Piloto'), ('IV', 'Ingeniero de vuelo'), ('JT', 'Jefe de Tripulacion'), ('TV', 'Tecnico de vuelo'), ('ART', 'Artillero'), ('CMA', 'Comandante de misión aérea'), ('OMI', 'Operador de Mision'), ('OVE', 'Operador de vehiculo')], max_length=3)),
                ('air_craft_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts_model_crew', to='index.AirCraftModel')),
                ('air_craft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts_type_crew', to='index.AirCraftType')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_crew', to='index.Rank')),
            ],
        ),
        migrations.AddField(
            model_name='aviationmission',
            name='mission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviation_mission_type', to='index.MissionType'),
        ),
        migrations.AddField(
            model_name='aviationevent',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviation_events_municipalities', to='index.Municipality'),
        ),
        migrations.CreateModel(
            name='AirCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_crews', to='index.Crew')),
                ('flight_reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_flight_report', to='index.FlightReport')),
            ],
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='air_craft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraftmodels', to='index.AirCraftType'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='air_craft_models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_models', to='index.AirCraftModel'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='air_craft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_types', to='index.AirCraftType'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_municipalities', to='index.Municipality'),
        ),
    ]
