# Generated by Django 3.0.3 on 2020-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200309_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviationevent',
            name='name',
            field=models.CharField(choices=[('DB', 'Daño de batalla'), ('BASH', 'BASH - Bird/wildlife aircraft strike hazzard'), ('FOD', 'FOD - Foreign object damage'), ('CFIT', 'CFIT - Controlled Flight InTo Terrain'), ('CO', 'Colision'), ('IP', 'Incursión de pista')], max_length=4),
        ),
    ]
