# Generated by Django 3.0.3 on 2020-05-11 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_assignedhourmajoroperationaircraftmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedHourAgreementAircraftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_hours', models.FloatField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agreement', to='index.Agreement')),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agreement_aircraft_model', to='index.AirCraftModel')),
            ],
        ),
    ]
