# Generated by Django 3.0.3 on 2020-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_assignedhouragreementaircraftmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
