# Generated by Django 3.0.3 on 2020-03-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200309_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightreport',
            name='mission',
        ),
        migrations.AddField(
            model_name='flightreport',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_agreements', to='index.Agreement'),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='aviation_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_aviation_missions', to='index.AviationMission'),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='major_operative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_major_operative_units', to='index.MajorOperativeUnit'),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='tactic_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_tactic_units', to='index.TacticUnit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightreport',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_aircrafts', to='index.AirCraft'),
        ),
        migrations.AlterField(
            model_name='flightreport',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_reports_configurations', to='index.Configuration'),
        ),
    ]
