# Generated by Django 3.0.3 on 2020-05-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_aircraft_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major_operative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_operative_unit_users', to='index.MajorOperativeUnit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minor_operative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_operative_unit_users', to='index.MinorOperativeUnit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tactic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tactic_unit_users', to='index.TacticUnit'),
        ),
    ]
