# Generated by Django 3.0.3 on 2020-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200311_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='next_inspection_hours',
            field=models.FloatField(default=0),
        ),
    ]
