# Generated by Django 3.0.3 on 2020-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200317_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_Vehicle_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_crew_chief',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_flight_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_flight_technician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_gunner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_mission_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_pam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='has_pilot',
            field=models.BooleanField(default=False),
        ),
    ]
