# Generated by Django 3.0.3 on 2020-03-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200317_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraftmodel',
            old_name='has_Vehicle_operator',
            new_name='has_vehicle_operator',
        ),
    ]
