# Generated by Django 2.2.4 on 2020-04-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20200428_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='hours_available',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='merger_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='re_asign',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='minoroperativeunit',
            name='major_operative_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_operative_units', to='index.MajorOperativeUnit'),
        ),
    ]
