# Generated by Django 2.2.4 on 2020-04-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20200429_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='type_inspection',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
