# Generated by Django 3.0.3 on 2020-04-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_aircraft_type_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='code',
            field=models.IntegerField(default=1, error_messages={'unique': 'Ya existe este usuario.'}, unique=True),
        ),
    ]
